# Generated by Django 3.0.5 on 2020-05-03 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=1000)),
                ('year', models.CharField(max_length=200)),
                ('journal', models.CharField(max_length=200)),
                ('citation', models.CharField(max_length=1000)),
                ('study_type', models.CharField(max_length=200)),
                ('clarity', models.CharField(max_length=1000)),
                ('valid_methods', models.CharField(max_length=1000)),
                ('results_importance', models.CharField(max_length=1000)),
                ('generalisability', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.CharField(max_length=1000)),
                ('review_date', models.DateTimeField(verbose_name='Date Reviewed')),
            ],
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='review',
            name='paper_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Reviews'),
        ),
    ]
