# Generated by Django 3.0.5 on 2020-05-03 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200503_2019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Article_Review',
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='User_Review',
        ),
    ]
