# Generated by Django 3.0.5 on 2020-05-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20200503_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_review',
            name='url',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article_review',
            name='generalisability',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article_review',
            name='results_importance',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article_review',
            name='take_home',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article_review',
            name='valid_methods',
            field=models.TextField(),
        ),
    ]
