# Generated by Django 3.0.5 on 2020-05-03 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20200503_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_review',
            name='review_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Reviewed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article_review',
            name='citation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article_review',
            name='paper_name',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='User_Review',
        ),
    ]
